### ISSUE TITLE
feat: parse JSON from <script> of a page

### ISSUE THREAD

**Issue by gildesmarais** [html2rss/html2rss#103]
Many pages include the interesting information in JSON in a script tag somewhere (e.g. to use it in a SPA).

Now, since every script tag looks the same and just the content matters, we'd need to select the correct once of many first. From there on, it should be the same process to generate the RSS.

- [ ] select the correct script tag
- [ ] handle global variable assignment in script-tag
- [ ] support parsing json from <script>

Sometimes it's not JSON, but javascript (e.g. to assign JS objects to a global variable. Nuxt does that).

Javascript's `JSON.stringify` simply ignores non-json-able notations when serializing.

```
JSON.stringify({ "a": "Bbb", "b": function() { alert() }, "c": "d"})
=> '{"a":"Bbb","c":"d"}'
```

This behaviour is desirable for these cases.

**Comment by nm2k** [comment]
+1

**Comment by gildesmarais** [comment]
With auto_source, parsing Schema Articles works. 

For scraping SPAs, https://github.com/html2rss/html2rss/issues/204 seems to be the less brittle approach.

**Comment by gildesmarais** [comment]
With auto_source Schema Scraper and alternatively rendering SPA using browserless strategy, I consider this enhancement to be delivered.
