### ISSUE TITLE
Cant run after installing

### ISSUE THREAD

**Issue by seededplyr** [html2rss/html2rss#119]
I am stuck at the very start, I have some experience with the linux command line but none in ruby or ruby applications, I have just installed ruby on my headless arch box, then installed the html2rss gem with "gem install html2rss" also confirmed the ruby bin is in path but cant get html2rss to run, also checking the ruby bin shows no application in there called html2rss

PS: I was apprehensive to ask what seems to be a very simple question which surely must be answered already in several places, but my google kungfu suddenly seems to be very weak cause couple of hours in to my research and still no answer

**Comment by gildesmarais** [comment]
Hi!

Sorry for the late reply... The notification about this issue got swamped by others and moved down the list.

The CLI is not officially released yet => the version you installed does not have the CLI, yet. I'm (slowly) preparing a "1.0" release. That will take some time tho. 

I recommend to check out the Docker image of [html2rss-web](https://github.com/html2rss/html2rss-web) which uses the latest development version of this gem. 
Check the screenshot in https://github.com/html2rss/html2rss-web/issues/337#issuecomment-850301807 at Headline 3 to see how to use the CLI within Docker.

Hope it helps! :)

**Comment by seededplyr** [comment]
> 
> 
> Hi!
> 
> Sorry for the late reply... The notification about this issue got swamped by others and moved down the list.
> 
> The CLI is not officially released yet => the version you installed does not have the CLI, yet. I'm (slowly) preparing a "1.0" release. That will take some time tho.
> 
> I recommend to check out the Docker image of [html2rss-web](https://github.com/html2rss/html2rss-web) which uses the latest development version of this gem.
> Check the screenshot in [html2rss/html2rss-web#337 (comment)](https://github.com/html2rss/html2rss-web/issues/337#issuecomment-850301807) at Headline 3 to see how to use the CLI within Docker.
> 
> Hope it helps! :)

thank you very much for the reply mate, will give the docker image a go cheers :)
