### ISSUE TITLE
Allow custom GUID

### ISSUE THREAD

**Issue by sabishiii** [html2rss/html2rss#125]
Right now the GUID is just an automatically generated hash of each item's title or description, over which the user's feed configuration has no control. It would be great if the guid could be treated as yet another selector that the user could configure, so that custom behaviors could be defined. For example, keeping the GUID the same if the title changes just slightly, or forcing an update if a selector other than the title or description change(for example, the "link" selector).

Thanks a lot for developing this package!

**Comment by gildesmarais** [comment]
Hey,

I favor the idea of a customizable selection of the item's GUID value.

OTOH, I feel the auto-generated GUID of `title`+`description` works quite well for most of my use cases. It should remain the default behavior.

Making a `guid` selector accept an array of selectors to use (analog to the categories) would be most flexible. Example in YAML:

```yaml
channel:
  # ...
selectors:
  # ...
  guid:
    - link
  link:
    selector: 'a'
    # ...
```

What do you think of this approach?

**Comment by sabishiii** [comment]
Hi @gildesmarais, your approach looks great to me. I agree that the customizable GUID should be the exception and used only by setting an explicit override in the feed configuration. Thanks for the quick reply! :)

**Comment by gildesmarais** [comment]
Done. Feel free to check it out by using the gem code via git.
