### ISSUE TITLE
Trouble installing executable

### ISSUE THREAD

**Issue by Friptick** [html2rss/html2rss#161]
Sorry, small support request (after much searching for a solution). 

`gem install --user-install html2rss` correctly installs the gem to `$HOME/.local/share/gem/ruby/3.0.0/gems`. But no shell executable seems to be created anywhere, and certainly not in `$HOME/.local/share/gem/ruby/3.0.0/bin` (which is in $PATH).

And so no `html2rss` command is available. I would like to try the CLI.

What am I doing wrong?

**Comment by Friptick** [comment]
Update. Noticed the Ruby 3.1 requirement in the docs. Re-installed with 3.1.0. Still no executable.

Giving up for now.

**Comment by Friptick** [comment]
Understood. Thanks for the suggestions.

**Comment by gildesmarais** [comment]
Finally released a new version. You can install it with `gem install html2rss`.

https://rubygems.org/gems/html2rss/versions/0.10.0
