### ISSUE TITLE
Fail to install on ARM server

### ISSUE THREAD

**Issue by plgagne** [html2rss/html2rss#180]
Using an AWS ARM server running Debian, the following error is produced: 

gem install html2rss
Building native extensions. This could take a while...
ERROR:  Error installing html2rss:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/3.1.0/gems/nokogumbo-2.0.5/ext/nokogumbo
/usr/bin/ruby3.1 -I /usr/lib/ruby/vendor_ruby -r ./siteconf20240630-1015-ncwk3p.rb extconf.rb
checking for whether -I/var/lib/gems/3.1.0/gems/nokogiri-1.16.6-aarch64-linux/ext/nokogiri is accepted as CFLAGS... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/$(RUBY_BASE_NAME)3.1
	--with-libxml2
	--without-libxml2
/usr/lib/ruby/3.1.0/mkmf.rb:498:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /usr/lib/ruby/3.1.0/mkmf.rb:624:in `block in try_compile'
	from /usr/lib/ruby/3.1.0/mkmf.rb:571:in `with_werror'
	from /usr/lib/ruby/3.1.0/mkmf.rb:624:in `try_compile'
	from /usr/lib/ruby/3.1.0/mkmf.rb:688:in `try_cflags'
	from /usr/lib/ruby/3.1.0/mkmf.rb:694:in `block (2 levels) in append_cflags'
	from /usr/lib/ruby/3.1.0/mkmf.rb:1007:in `block in checking_for'
	from /usr/lib/ruby/3.1.0/mkmf.rb:362:in `block (2 levels) in postpone'
	from /usr/lib/ruby/3.1.0/mkmf.rb:332:in `open'
	from /usr/lib/ruby/3.1.0/mkmf.rb:362:in `block in postpone'
	from /usr/lib/ruby/3.1.0/mkmf.rb:332:in `open'
	from /usr/lib/ruby/3.1.0/mkmf.rb:358:in `postpone'
	from /usr/lib/ruby/3.1.0/mkmf.rb:1006:in `checking_for'
	from /usr/lib/ruby/3.1.0/mkmf.rb:693:in `block in append_cflags'
	from /usr/lib/ruby/3.1.0/mkmf.rb:692:in `each'
	from /usr/lib/ruby/3.1.0/mkmf.rb:692:in `append_cflags'
	from extconf.rb:76:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /var/lib/gems/3.1.0/extensions/aarch64-linux/3.1.0/nokogumbo-2.0.5/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/3.1.0/gems/nokogumbo-2.0.5 for inspection.
Results logged to /var/lib/gems/3.1.0/extensions/aarch64-linux/3.1.0/nokogumbo-2.0.5/gem_make.out

The log contains the following: 

LD_LIBRARY_PATH=.:/usr/lib/aarch64-linux-gnu "aarch64-linux-gnu-gcc -o conftest -I/usr/in>
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return !!argv[argc];
6: }
/* end */

**Comment by gildesmarais** [comment]
Hi, thanks for reporting an issue. I've released a new version. Could you please try `gem install html2rss` again and report back if the issue persists? Thank you.
